version: 0.{build}

os: Windows Server 2012 R2

init:
  - git config --global core.autocrlf input

clone_folder: c:\projects\ED

platform: x86
configuration: Release

build:
  project: c:\projects\ED\ElDorito.vcxproj

after_build:
  - cd C:\projects\ED\bin\Release\
  - copy /y mtndew.dll ..\..\mtndew.dll

artifacts:
  - path: mtndew.dll
    name: mtndew.dll