version: 0.5.1.{build}

# Operating system (build VM template)
os: Windows Server 2012 R2

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\ED

platform: x86
configuration: Release

build:
  project: c:\projects\ED\ElDorito.vcxproj      # path to Visual Studio solution or project

# scripts to run before build
before_build:
  - echo Running generate_vs2013_sln_files.bat...
  - cd c:\projects\ED
  - generate_vs2013_sln_files.bat
  - 7z a c:\projects\ED\ED.7z * -t7z m0=lzma -mx=9 -mfb=64 -md=32m -ms=on
  - appveyor PushArtifact c:\projects\ED\ED.7z

# scripts to run after build
after_build:
  - cd C:\projects\ED\Release\

artifacts:
  - path: mtndew.dll
    name: mtndew.dll