version: 0.{build}

skip_tags: true

skip_branch_with_pr: true

environment:
  discord:
    secure: J9/ytFq45v8CySuImAyD49rwkimnPu8NZnAqaKE+9D3xkcs7Vv28k8DR/hoCXmxnM/UKDRnVg8Yj7v6HlET0AvHtsVbJ+MhtFsGlNmVYVbBPZLRy6EDS28spVmE8ZLUsW45OOPR3IrwyHlWP4paOezV6zHA9T8yFuIq2/bJcGA8=


os: Windows Server 2012 R2

init:
  - git config --global core.autocrlf input

clone_folder: c:\projects\ED

platform: x86
configuration: Release

build:
  project: c:\projects\ED\ElDorito.vcxproj

after_build:
  - cd C:\projects\ED\bin\Release\
  - copy /y mtndew.dll ..\..\mtndew.dll

artifacts:
  - path: mtndew.dll
    name: mtndew.dll

deploy:
  - provider: GitHub
    tag: 0
    release: v0.{build}
    auth_token:
      secure: NtgoY7/UXsMaWp1KTWAsCp6dc9kq6ryIajWs4A4uY+7+Q7xVfQiAnXRiba5wGOaQ
    artifact: mtndew.dll
    draft: true
    prerelease: true
    force_update: true

notifications:
  - provider: Webhook
    url: $(discord)
    method: POST
    on_build_success: true
    on_build_failure: false
    on_build_status_changed: false