version: 0.{build}

skip_tags: true

skip_branch_with_pr: true


os: Windows Server 2012 R2

init:
  - git config --global core.autocrlf input

clone_folder: c:\projects\ED

platform: x86
configuration: Release

build:
  project: c:\projects\ED\build\ElDorito.vcxproj


before_build:
  - cd c:\projects\ED
  - generate_vs2013_sln_files.bat

after_build:
  - cd C:\projects\ED\build\Release\
  - copy /y mtndew.dll ..\..\mtndew.dll

artifacts:
  - path: mtndew.dll
    name: mtndew.dll

deploy:
  - provider: GitHub
    tag: 0
    release: v0
    auth_token:
      secure: NtgoY7/UXsMaWp1KTWAsCp6dc9kq6ryIajWs4A4uY+7+Q7xVfQiAnXRiba5wGOaQ
    artifact: mtndew.dll
    draft: false
    prerelease: true
    force_update: true