version: 0.5.1.{build}

# Operating system (build VM template)
os: Windows Server 2012 R2

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\ED

platform: x86
configuration: Release

build:
  project: c:\projects\ED\ElDorito.vcxproj      # path to Visual Studio solution or project

# scripts to run before build
before_build:
  - cd c:\projects\ED

# scripts to run after build
after_build:
  - cd C:\projects\ED\Release\

artifacts:
  - path: mtndew.dll
    name: mtndew.dll